---
title: "01_binning"
author: "Kaushik Surej"
date: "2026-07-15"
output: html_document
---

## Step 2: Binning of the programme with metabat
```bash
metabat2 -i assembly_bbd_ordered.fasta -a depths_bbd.txt --cvExt -o bins_bbd/metabat --seed 5
```
 Binning with metabat is considered as an important step because it helps in grouping contigs that are likely to originate within the bacterial genome
 
The results that have been produced is a collection of metagenome assembled genomes called (MAGs) which might or might not represent a particular species or population present

## Step 3: Bin quality with checkm
```bash
samtools faidx ../flye/bbd/assembly.fasta contig_116 > bins_bbd/contig_116.fa
```

### Information about the largest contig that was assembled:

- contig116: size was roughly at about 4.7 Mb
- bin name: contig_116
 
(i) contig_116 was added as its own bin because of metabat2's feature where it more often than not rejects or excludes the binning application of large contigs from automatic binning

(ii) Due to the large size proportions of contig_116, we could potentially hypothesize that this contig represents a major chunk of the genome that is currently under observation